spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/custom_database
    username: postgres_user
    password: postgres_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      stop:
        command: down
